#!/usr/bin/env bash
"""
Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02.)
1. The name of the custom HTTP header must be X-Served-By
2. The value of the custom HTTP header must be the hostname of the server Nginx is running on
"""
# Running updates
sudo apt-get update
#installing nginx
sudo apt-get -y install nginx

#configuring Nginx by allowing requests at port 80(HTTP) 
sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html

#Read and write permission for everyone and write permission for the owner. 
sudo chmod -R 755/var/www

#Creating a web page
echo "Hellow world!" > /var/www/html/index.html

#404 error page
echo "Ceci n'est pas une page" > /var/www/html/404.html

replacement_string="server_name_; \n\tadd_header X-Served-By \$hostname;\n\trewite ^\/redirect_me https:\/\/www.blog.olukoyainc.com permanent;"
sudo sed -i "s/server_name _;/$replacement_string" /ect/nginx/sites-enabled/default

replacement_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$replacement_string/" /ect/nginx/sites-enabled/default

sudo service nginx start
