#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02.)
# 1. The name of the custom HTTP header must be X-Served-By
# 2. The value of the custom HTTP header must be the hostname of the server Nginx is running on

# Running updates
sudo apt-get update
#installing nginx
sudo apt-get -y install nginx

#configuring Nginx by allowing requests at port 80(HTTP)
sudo ufw allow 'Nginx HTTP'
#Create directory for web page and error pages
sudo mkdir -p /var/www/html /var/www/error

#Read and write permission for everyone and write permission for the owner.
sudo chmod -R 755 /var/www

#Creating a web page
echo "Hellow world!" | sudo tee -a /var/www/html/index.html

#404 error page
echo "Ceci n'est pas une page" | sudo tee -a /var/www/html/404.html

server_config=\
"server {
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html;
        server_name _;
        add_header X-Served-By \$hostname;
        location / {
                try_files \$uri \$uri/ = 404;
        }
        if (\$request_filename ~ redirect_me){
                rewrite ^ https://www.blog.ehoneahobed.com permanent;
        {
        error_page 404 /404.html;
        location = /404.html{
                internal;
        }

}"
echo "$server_config" | sudo tee -a /etc/nginx/sites-enabled/default
sudo service nginx restart
