#!/usr/bin/env bash
#script that:
# 1. Creates the file /var/run/myscript.pid containing its PID
# 2. Displays To infinity and beyond indefinitely
# 3. Displays I hate the kill command when receiving a SIGTERM signal.
# 4. Displays Y U no love me?! when receiving a SIGINT signal
# 5. Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal.

terminator() {
  rm /var/run/myscript.pid
  exit
}

echo "$$" > /var/run/myscript.pid

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && terminator' SIGTERM
  trap 'terminator' SIGQUITgit 
done
