#!/usr/bin/env bash
#script that displays numbers from 1 to 100.
# thn 1. Displays FizzBuzz when the number is a multiple of 3 and 5
#     2. Displays Fizz when the number is multiple of 3
#     3. Displays Buzz when the number is a multiple of 5
#     4. Otherwise, displays the number
#     5. In a list format

for numb in {1..100}
do
 if (( numb % 3 == 0 && numb % 5 == 0 ))
 then
   echo "FizzBuzz"
 elif (( numb % 3 == 0 ))
 then
   echo "Fizz"
 elif (( numb % 5 == 0 ))
 then
   echo "Buzz"
 else
   echo "$numb"
   fi
  done
