#!/usr/bin/env bash
#Fixing the server to rin on port 8080
sed -i "s/#user www-data/user nginx/" /etc/nginx.conf
sed -i "s/80/8080/g" /etc/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
